.TH "FlyingWormConsole3.LiteNetLib.INtpEventListener" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib.INtpEventListener
.SH SYNOPSIS
.br
.PP
.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\fP에 의해 상속되었습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "void \fBOnNtpResponse\fP (\fBNtpPacket\fP packet)"
.br
.RI "Ntp response "
.in -1c
.SH "상세한 설명"
.PP 
\fBINetEventListener\&.cs\fP 파일의 \fB117\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "void FlyingWormConsole3\&.LiteNetLib\&.INtpEventListener\&.OnNtpResponse (\fBNtpPacket\fP packet)"

.PP
Ntp response 
.PP
\fB매개변수\fP
.RS 4
\fIpacket\fP 
.RE
.PP


.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
