.TH "FlyingWormConsole3.ConsoleProRemoteServer" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.ConsoleProRemoteServer
.SH SYNOPSIS
.br
.PP
.PP
MonoBehaviour를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.in -1c
.SS "Public 속성"

.in +1c
.ti -1c
.RI "bool \fBuseNATPunch\fP = false"
.br
.ti -1c
.RI "int \fBport\fP = 51000"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBConsoleProRemoteServer\&.cs\fP 파일의 \fB36\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "void FlyingWormConsole3\&.ConsoleProRemoteServer\&.Awake ()"

.PP
\fBConsoleProRemoteServer\&.cs\fP 파일의 \fB53\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 데이터 문서화"
.PP 
.SS "int FlyingWormConsole3\&.ConsoleProRemoteServer\&.port = 51000"

.PP
\fBConsoleProRemoteServer\&.cs\fP 파일의 \fB40\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.ConsoleProRemoteServer\&.useNATPunch = false"

.PP
\fBConsoleProRemoteServer\&.cs\fP 파일의 \fB39\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
