.TH "FlyingWormConsole3.LiteNetLib.Utils.NetSerializer" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib.Utils.NetSerializer
.SH SYNOPSIS
.br
.PP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "void \fBRegisterNestedType< T >\fP ()"
.br
.RI "Register custom property type "
.ti -1c
.RI "void \fBRegisterNestedType< T >\fP (Func< T > constructor)"
.br
.RI "Register custom property type "
.ti -1c
.RI "void \fBRegisterNestedType< T >\fP (Action< \fBNetDataWriter\fP, T > writer, Func< \fBNetDataReader\fP, T > reader)"
.br
.RI "Register custom property type "
.ti -1c
.RI "\fBNetSerializer\fP ()"
.br
.ti -1c
.RI "\fBNetSerializer\fP (int maxStringLength)"
.br
.ti -1c
.RI "void \fBRegister< T >\fP ()"
.br
.RI "
.PP
\fB예외\fP
.RS 4
\fI\fBInvalidTypeException\fP\fP \fIT\fP 's fields are not supported, or it has no fields
.RE
.PP
"
.ti -1c
.RI "T \fBDeserialize< T >\fP (\fBNetDataReader\fP reader)"
.br
.RI "Reads packet with known type "
.ti -1c
.RI "bool \fBDeserialize< T >\fP (\fBNetDataReader\fP reader, T target)"
.br
.RI "Reads packet with known type (non alloc variant) "
.ti -1c
.RI "void \fBSerialize< T >\fP (\fBNetDataWriter\fP writer, T obj)"
.br
.RI "Serialize object to \fBNetDataWriter\fP (fast) "
.ti -1c
.RI "byte[] \fBSerialize< T >\fP (T obj)"
.br
.RI "Serialize object to byte array "
.in -1c
.SH "상세한 설명"
.PP 
\fBNetSerializer\&.cs\fP 파일의 \fB19\fP 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetSerializer\&.NetSerializer ()"

.PP
\fBNetSerializer\&.cs\fP 파일의 \fB570\fP 번째 라인에서 정의되었습니다\&.
.SS "FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetSerializer\&.NetSerializer (int maxStringLength)"

.PP
\fBNetSerializer\&.cs\fP 파일의 \fB574\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "T FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetSerializer\&.Deserialize< T > (\fBNetDataReader\fP reader)"

.PP
Reads packet with known type 
.PP
\fB매개변수\fP
.RS 4
\fIreader\fP \fBNetDataReader\fP with packet
.RE
.PP
\fB반환값\fP
.RS 4
Returns packet if packet in reader is matched type
.RE
.PP
\fB예외\fP
.RS 4
\fI\fBInvalidTypeException\fP\fP \fIT\fP 's fields are not supported, or it has no fields
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetSerializer\&.cs\fP 파일의 \fB686\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetSerializer\&.Deserialize< T > (\fBNetDataReader\fP reader, T target)"

.PP
Reads packet with known type (non alloc variant) 
.PP
\fB매개변수\fP
.RS 4
\fIreader\fP \fBNetDataReader\fP with packet
.br
\fItarget\fP Deserialization target
.RE
.PP
\fB반환값\fP
.RS 4
Returns true if packet in reader is matched type
.RE
.PP
\fB예외\fP
.RS 4
\fI\fBInvalidTypeException\fP\fP \fIT\fP 's fields are not supported, or it has no fields
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetSerializer\&.cs\fP 파일의 \fB708\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetSerializer\&.Register< T > ()"

.PP

.PP
\fB예외\fP
.RS 4
\fI\fBInvalidTypeException\fP\fP \fIT\fP 's fields are not supported, or it has no fields
.RE
.PP

.PP
\fBNetSerializer\&.cs\fP 파일의 \fB675\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetSerializer\&.RegisterNestedType< T > ()"

.PP
Register custom property type 
.PP
\fB템플릿 파라메터\fP
.RS 4
\fIT\fP \fBINetSerializable\fP structure
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIstruct\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.PP
\fBNetSerializer\&.cs\fP 파일의 \fB541\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetSerializer\&.RegisterNestedType< T > (Action< \fBNetDataWriter\fP, T > writer, Func< \fBNetDataReader\fP, T > reader)"

.PP
Register custom property type 
.PP
\fB템플릿 파라메터\fP
.RS 4
\fIT\fP Any packet
.RE
.PP
\fB매개변수\fP
.RS 4
\fIwriter\fP custom type writer
.br
\fIreader\fP custom type reader
.RE
.PP

.PP
\fBNetSerializer\&.cs\fP 파일의 \fB561\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetSerializer\&.RegisterNestedType< T > (Func< T > constructor)"

.PP
Register custom property type 
.PP
\fB템플릿 파라메터\fP
.RS 4
\fIT\fP \fBINetSerializable\fP class
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.PP
\fBNetSerializer\&.cs\fP 파일의 \fB550\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetSerializer\&.Serialize< T > (\fBNetDataWriter\fP writer, T obj)"

.PP
Serialize object to \fBNetDataWriter\fP (fast) 
.PP
\fB매개변수\fP
.RS 4
\fIwriter\fP Serialization target \fBNetDataWriter\fP
.br
\fIobj\fP Object to serialize
.RE
.PP
\fB예외\fP
.RS 4
\fI\fBInvalidTypeException\fP\fP \fIT\fP 's fields are not supported, or it has no fields
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetSerializer\&.cs\fP 파일의 \fB728\fP 번째 라인에서 정의되었습니다\&.
.SS "byte[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetSerializer\&.Serialize< T > (T obj)"

.PP
Serialize object to byte array 
.PP
\fB매개변수\fP
.RS 4
\fIobj\fP Object to serialize
.RE
.PP
\fB반환값\fP
.RS 4
byte array with serialized data
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetSerializer\&.cs\fP 파일의 \fB738\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
