.TH "FlyingWormConsole3.LiteNetLib.EventBasedNetListener" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib.EventBasedNetListener
.SH SYNOPSIS
.br
.PP
.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.INetEventListener\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.IDeliveryEventListener\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.INtpEventListener\fP를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "delegate void \fBOnPeerConnected\fP (\fBNetPeer\fP peer)"
.br
.RI "New remote peer connected to host, or client connected to remote host "
.ti -1c
.RI "delegate void \fBOnPeerDisconnected\fP (\fBNetPeer\fP peer, \fBDisconnectInfo\fP disconnectInfo)"
.br
.RI "Peer disconnected "
.ti -1c
.RI "delegate void \fBOnNetworkError\fP (IPEndPoint endPoint, SocketError socketError)"
.br
.RI "Network error (on send or receive) "
.ti -1c
.RI "delegate void \fBOnNetworkReceive\fP (\fBNetPeer\fP peer, \fBNetPacketReader\fP reader, \fBDeliveryMethod\fP deliveryMethod)"
.br
.RI "Received some data "
.ti -1c
.RI "delegate void \fBOnNetworkReceiveUnconnected\fP (IPEndPoint remoteEndPoint, \fBNetPacketReader\fP reader, \fBUnconnectedMessageType\fP messageType)"
.br
.RI "Received unconnected message "
.ti -1c
.RI "delegate void \fBOnNetworkLatencyUpdate\fP (\fBNetPeer\fP peer, int latency)"
.br
.RI "Latency information updated "
.ti -1c
.RI "delegate void \fBOnConnectionRequest\fP (\fBConnectionRequest\fP request)"
.br
.RI "On peer connection requested "
.ti -1c
.RI "delegate void \fBOnDeliveryEvent\fP (\fBNetPeer\fP peer, object userData)"
.br
.ti -1c
.RI "delegate void \fBOnNtpResponseEvent\fP (\fBNtpPacket\fP packet)"
.br
.ti -1c
.RI "void \fBClearPeerConnectedEvent\fP ()"
.br
.ti -1c
.RI "void \fBClearPeerDisconnectedEvent\fP ()"
.br
.ti -1c
.RI "void \fBClearNetworkErrorEvent\fP ()"
.br
.ti -1c
.RI "void \fBClearNetworkReceiveEvent\fP ()"
.br
.ti -1c
.RI "void \fBClearNetworkReceiveUnconnectedEvent\fP ()"
.br
.ti -1c
.RI "void \fBClearNetworkLatencyUpdateEvent\fP ()"
.br
.ti -1c
.RI "void \fBClearConnectionRequestEvent\fP ()"
.br
.ti -1c
.RI "void \fBClearDeliveryEvent\fP ()"
.br
.ti -1c
.RI "void \fBClearNtpResponseEvent\fP ()"
.br
.in -1c
.SS "이벤트"

.in +1c
.ti -1c
.RI "\fBOnPeerConnected\fP \fBPeerConnectedEvent\fP"
.br
.ti -1c
.RI "\fBOnPeerDisconnected\fP \fBPeerDisconnectedEvent\fP"
.br
.ti -1c
.RI "\fBOnNetworkError\fP \fBNetworkErrorEvent\fP"
.br
.ti -1c
.RI "\fBOnNetworkReceive\fP \fBNetworkReceiveEvent\fP"
.br
.ti -1c
.RI "\fBOnNetworkReceiveUnconnected\fP \fBNetworkReceiveUnconnectedEvent\fP"
.br
.ti -1c
.RI "\fBOnNetworkLatencyUpdate\fP \fBNetworkLatencyUpdateEvent\fP"
.br
.ti -1c
.RI "\fBOnConnectionRequest\fP \fBConnectionRequestEvent\fP"
.br
.ti -1c
.RI "\fBOnDeliveryEvent\fP \fBDeliveryEvent\fP"
.br
.ti -1c
.RI "\fBOnNtpResponseEvent\fP \fBNtpResponseEvent\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBINetEventListener\&.cs\fP 파일의 \fB126\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.ClearConnectionRequestEvent ()"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB178\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.ClearDeliveryEvent ()"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB183\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.ClearNetworkErrorEvent ()"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB158\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.ClearNetworkLatencyUpdateEvent ()"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB173\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.ClearNetworkReceiveEvent ()"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB163\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.ClearNetworkReceiveUnconnectedEvent ()"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB168\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.ClearNtpResponseEvent ()"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB188\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.ClearPeerConnectedEvent ()"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB148\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.ClearPeerDisconnectedEvent ()"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB153\fP 번째 라인에서 정의되었습니다\&.
.SS "delegate void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.OnConnectionRequest (\fBConnectionRequest\fP request)"

.PP
On peer connection requested 
.PP
\fB매개변수\fP
.RS 4
\fIrequest\fP Request information (EndPoint, internal id, additional data)
.RE
.PP

.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.INetEventListener\fP를 구현\&.
.SS "delegate void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.OnDeliveryEvent (\fBNetPeer\fP peer, object userData)"

.SS "delegate void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.OnNetworkError (IPEndPoint endPoint, SocketError socketError)"

.PP
Network error (on send or receive) 
.PP
\fB매개변수\fP
.RS 4
\fIendPoint\fP From endPoint (can be null)
.br
\fIsocketError\fP Socket error
.RE
.PP

.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.INetEventListener\fP를 구현\&.
.SS "delegate void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.OnNetworkLatencyUpdate (\fBNetPeer\fP peer, int latency)"

.PP
Latency information updated 
.PP
\fB매개변수\fP
.RS 4
\fIpeer\fP Peer with updated latency
.br
\fIlatency\fP latency value in milliseconds
.RE
.PP

.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.INetEventListener\fP를 구현\&.
.SS "delegate void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.OnNetworkReceive (\fBNetPeer\fP peer, \fBNetPacketReader\fP reader, \fBDeliveryMethod\fP deliveryMethod)"

.PP
Received some data 
.PP
\fB매개변수\fP
.RS 4
\fIpeer\fP From peer
.br
\fIreader\fP DataReader containing all received data
.br
\fIdeliveryMethod\fP Type of received packet
.RE
.PP

.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.INetEventListener\fP를 구현\&.
.SS "delegate void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.OnNetworkReceiveUnconnected (IPEndPoint remoteEndPoint, \fBNetPacketReader\fP reader, \fBUnconnectedMessageType\fP messageType)"

.PP
Received unconnected message 
.PP
\fB매개변수\fP
.RS 4
\fIremoteEndPoint\fP From address (IP and Port)
.br
\fIreader\fP Message data
.br
\fImessageType\fP Message type (simple, discovery request or response)
.RE
.PP

.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.INetEventListener\fP를 구현\&.
.SS "delegate void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.OnNtpResponseEvent (\fBNtpPacket\fP packet)"

.SS "delegate void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.OnPeerConnected (\fBNetPeer\fP peer)"

.PP
New remote peer connected to host, or client connected to remote host 
.PP
\fB매개변수\fP
.RS 4
\fIpeer\fP Connected peer object
.RE
.PP

.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.INetEventListener\fP를 구현\&.
.SS "delegate void FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.OnPeerDisconnected (\fBNetPeer\fP peer, \fBDisconnectInfo\fP disconnectInfo)"

.PP
Peer disconnected 
.PP
\fB매개변수\fP
.RS 4
\fIpeer\fP disconnected peer
.br
\fIdisconnectInfo\fP additional info about reason, errorCode or data received with disconnect message
.RE
.PP

.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.INetEventListener\fP를 구현\&.
.SH "이벤트 문서화"
.PP 
.SS "\fBOnConnectionRequest\fP FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.ConnectionRequestEvent"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB144\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBOnDeliveryEvent\fP FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.DeliveryEvent"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB145\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBOnNetworkError\fP FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.NetworkErrorEvent"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB140\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBOnNetworkLatencyUpdate\fP FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.NetworkLatencyUpdateEvent"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB143\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBOnNetworkReceive\fP FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.NetworkReceiveEvent"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB141\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBOnNetworkReceiveUnconnected\fP FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.NetworkReceiveUnconnectedEvent"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB142\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBOnNtpResponseEvent\fP FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.NtpResponseEvent"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB146\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBOnPeerConnected\fP FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.PeerConnectedEvent"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB138\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBOnPeerDisconnected\fP FlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\&.PeerDisconnectedEvent"

.PP
\fBINetEventListener\&.cs\fP 파일의 \fB139\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
