.TH "FlyingWormConsole3.LiteNetLib" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib
.SH SYNOPSIS
.br
.PP
.SS "네임스페이스"

.in +1c
.ti -1c
.RI "namespace \fBLayers\fP"
.br
.ti -1c
.RI "namespace \fBUtils\fP"
.br
.in -1c
.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBBaseChannel\fP"
.br
.ti -1c
.RI "class \fBConnectionRequest\fP"
.br
.ti -1c
.RI "struct \fBDisconnectInfo\fP"
.br
.RI "Additional information about disconnection "
.ti -1c
.RI "class \fBEventBasedNatPunchListener\fP"
.br
.ti -1c
.RI "class \fBEventBasedNetListener\fP"
.br
.ti -1c
.RI "interface \fBIDeliveryEventListener\fP"
.br
.ti -1c
.RI "interface \fBINatPunchListener\fP"
.br
.ti -1c
.RI "interface \fBINetEventListener\fP"
.br
.ti -1c
.RI "interface \fBINetLogger\fP"
.br
.RI "Interface to implement for your own logger "
.ti -1c
.RI "interface \fBINtpEventListener\fP"
.br
.ti -1c
.RI "class \fBInvalidPacketException\fP"
.br
.ti -1c
.RI "class \fBNatPunchModule\fP"
.br
.RI "Module for UDP NAT Hole punching operations\&. Can be accessed from \fBNetManager\fP "
.ti -1c
.RI "class \fBNetConnectAcceptPacket\fP"
.br
.ti -1c
.RI "class \fBNetConnectRequestPacket\fP"
.br
.ti -1c
.RI "class \fBNetConstants\fP"
.br
.RI "Network constants\&. Can be tuned from sources for your purposes\&. "
.ti -1c
.RI "class \fBNetDebug\fP"
.br
.RI "Static class for defining your own \fBLiteNetLib\fP logger instead of Console\&.WriteLine or Debug\&.Log if compiled with UNITY flag "
.ti -1c
.RI "class \fBNetEvent\fP"
.br
.ti -1c
.RI "class \fBNetManager\fP"
.br
.RI "Main class for all network operations\&. Can be used as client and/or server\&. "
.ti -1c
.RI "class \fBNetPacket\fP"
.br
.ti -1c
.RI "class \fBNetPacketPool\fP"
.br
.ti -1c
.RI "class \fBNetPacketReader\fP"
.br
.ti -1c
.RI "class \fBNetPeer\fP"
.br
.RI "Network peer\&. Main purpose is sending messages to specific peer\&. "
.ti -1c
.RI "class \fBNetSocket\fP"
.br
.ti -1c
.RI "class \fBNetStatistics\fP"
.br
.ti -1c
.RI "class \fBNetUtils\fP"
.br
.RI "Some specific network utilities "
.ti -1c
.RI "class \fBReliableChannel\fP"
.br
.ti -1c
.RI "class \fBSequencedChannel\fP"
.br
.ti -1c
.RI "class \fBTooBigPacketException\fP"
.br
.in -1c
.SS "열거형 타입"

.in +1c
.ti -1c
.RI "enum \fBUnconnectedMessageType\fP { \fBBasicMessage\fP, \fBBroadcast\fP }"
.br
.RI "Type of message that you receive in OnNetworkReceiveUnconnected event "
.ti -1c
.RI "enum \fBDisconnectReason\fP { \fBConnectionFailed\fP, \fBTimeout\fP, \fBHostUnreachable\fP, \fBNetworkUnreachable\fP, \fBRemoteConnectionClose\fP, \fBDisconnectPeerCalled\fP, \fBConnectionRejected\fP, \fBInvalidProtocol\fP, \fBUnknownHost\fP, \fBReconnect\fP, \fBPeerToPeerConnection\fP }"
.br
.RI "Disconnect reason that you receive in OnPeerDisconnected event "
.ti -1c
.RI "enum \fBNatAddressType\fP { \fBInternal\fP, \fBExternal\fP }"
.br
.ti -1c
.RI "enum \fBDeliveryMethod\fP : byte { \fBUnreliable\fP = 4, \fBReliableUnordered\fP = 0, \fBSequenced\fP = 1, \fBReliableOrdered\fP = 2, \fBReliableSequenced\fP = 3 }"
.br
.RI "Sending method type "
.ti -1c
.RI "enum \fBNetLogLevel\fP { \fBWarning\fP, \fBError\fP, \fBTrace\fP, \fBInfo\fP }"
.br
.ti -1c
.RI "enum \fBIPv6Mode\fP { \fBDisabled\fP, \fBSeparateSocket\fP, \fBDualMode\fP }"
.br
.ti -1c
.RI "enum \fBConnectionState\fP : byte { \fBOutgoing\fP = 1 << 1, \fBConnected\fP = 1 << 2, \fBShutdownRequested\fP = 1 << 3, \fBDisconnected\fP = 1 << 4, \fBAny\fP = Outgoing | Connected | ShutdownRequested }"
.br
.RI "Peer connection state "
.ti -1c
.RI "enum \fBLocalAddrType\fP { \fBIPv4\fP = 1, \fBIPv6\fP = 2, \fBAll\fP = IPv4 | IPv6 }"
.br
.RI "Address type that you want to receive from NetUtils\&.GetLocalIp method "
.in -1c
.SH "열거형 타입 문서화"
.PP 
.SS "enum \fBFlyingWormConsole3\&.LiteNetLib\&.ConnectionState\fP : byte"

.PP
Peer connection state 
.PP
\fB열거형 멤버\fP
.in +1c
.TP
\fB\fIOutgoing \fP\fP
.TP
\fB\fIConnected \fP\fP
.TP
\fB\fIShutdownRequested \fP\fP
.TP
\fB\fIDisconnected \fP\fP
.TP
\fB\fIAny \fP\fP
.PP
\fBNetPeer\&.cs\fP 파일의 \fB17\fP 번째 라인에서 정의되었습니다\&.
.SS "enum \fBFlyingWormConsole3\&.LiteNetLib\&.DeliveryMethod\fP : byte"

.PP
Sending method type 
.PP
\fB열거형 멤버\fP
.in +1c
.TP
\fB\fIUnreliable \fP\fP
Unreliable\&. Packets can be dropped, can be duplicated, can arrive without order\&. 
.TP
\fB\fIReliableUnordered \fP\fP
Reliable\&. Packets won't be dropped, won't be duplicated, can arrive without order\&. 
.TP
\fB\fISequenced \fP\fP
Unreliable\&. Packets can be dropped, won't be duplicated, will arrive in order\&. 
.TP
\fB\fIReliableOrdered \fP\fP
Reliable and ordered\&. Packets won't be dropped, won't be duplicated, will arrive in order\&. 
.TP
\fB\fIReliableSequenced \fP\fP
Reliable only last packet\&. Packets can be dropped (except the last one), won't be duplicated, will arrive in order\&. Cannot be fragmented 
.PP
\fBNetConstants\&.cs\fP 파일의 \fB6\fP 번째 라인에서 정의되었습니다\&.
.SS "enum \fBFlyingWormConsole3\&.LiteNetLib\&.DisconnectReason\fP"

.PP
Disconnect reason that you receive in OnPeerDisconnected event 
.PP
\fB열거형 멤버\fP
.in +1c
.TP
\fB\fIConnectionFailed \fP\fP
.TP
\fB\fITimeout \fP\fP
.TP
\fB\fIHostUnreachable \fP\fP
.TP
\fB\fINetworkUnreachable \fP\fP
.TP
\fB\fIRemoteConnectionClose \fP\fP
.TP
\fB\fIDisconnectPeerCalled \fP\fP
.TP
\fB\fIConnectionRejected \fP\fP
.TP
\fB\fIInvalidProtocol \fP\fP
.TP
\fB\fIUnknownHost \fP\fP
.TP
\fB\fIReconnect \fP\fP
.TP
\fB\fIPeerToPeerConnection \fP\fP
.PP
\fBINetEventListener\&.cs\fP 파일의 \fB19\fP 번째 라인에서 정의되었습니다\&.
.SS "enum \fBFlyingWormConsole3\&.LiteNetLib\&.IPv6Mode\fP"

.PP
\fB열거형 멤버\fP
.in +1c
.TP
\fB\fIDisabled \fP\fP
.TP
\fB\fISeparateSocket \fP\fP
.TP
\fB\fIDualMode \fP\fP
.PP
\fBNetManager\&.cs\fP 파일의 \fB13\fP 번째 라인에서 정의되었습니다\&.
.SS "enum \fBFlyingWormConsole3\&.LiteNetLib\&.LocalAddrType\fP"

.PP
Address type that you want to receive from NetUtils\&.GetLocalIp method 
.PP
\fB열거형 멤버\fP
.in +1c
.TP
\fB\fIIPv4 \fP\fP
.TP
\fB\fIIPv6 \fP\fP
.TP
\fB\fIAll \fP\fP
.PP
\fBNetUtils\&.cs\fP 파일의 \fB13\fP 번째 라인에서 정의되었습니다\&.
.SS "enum \fBFlyingWormConsole3\&.LiteNetLib\&.NatAddressType\fP"

.PP
\fB열거형 멤버\fP
.in +1c
.TP
\fB\fIInternal \fP\fP
.TP
\fB\fIExternal \fP\fP
.PP
\fBNatPunchModule\&.cs\fP 파일의 \fB8\fP 번째 라인에서 정의되었습니다\&.
.SS "enum \fBFlyingWormConsole3\&.LiteNetLib\&.NetLogLevel\fP"

.PP
\fB열거형 멤버\fP
.in +1c
.TP
\fB\fIWarning \fP\fP
.TP
\fB\fIError \fP\fP
.TP
\fB\fITrace \fP\fP
.TP
\fB\fIInfo \fP\fP
.PP
\fBNetDebug\&.cs\fP 파일의 \fB20\fP 번째 라인에서 정의되었습니다\&.
.SS "enum \fBFlyingWormConsole3\&.LiteNetLib\&.UnconnectedMessageType\fP"

.PP
Type of message that you receive in OnNetworkReceiveUnconnected event 
.PP
\fB열거형 멤버\fP
.in +1c
.TP
\fB\fIBasicMessage \fP\fP
.TP
\fB\fIBroadcast \fP\fP
.PP
\fBINetEventListener\&.cs\fP 파일의 \fB10\fP 번째 라인에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
