.TH "FlyingWormConsole3.LiteNetLib.NetStatistics" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib.NetStatistics
.SH SYNOPSIS
.br
.PP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBIncrementPacketsSent\fP ()"
.br
.ti -1c
.RI "void \fBIncrementPacketsReceived\fP ()"
.br
.ti -1c
.RI "void \fBAddBytesSent\fP (long bytesSent)"
.br
.ti -1c
.RI "void \fBAddBytesReceived\fP (long bytesReceived)"
.br
.ti -1c
.RI "void \fBIncrementPacketLoss\fP ()"
.br
.ti -1c
.RI "void \fBAddPacketLoss\fP (long packetLoss)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "속성"

.in +1c
.ti -1c
.RI "long \fBPacketsSent\fP\fC [get]\fP"
.br
.ti -1c
.RI "long \fBPacketsReceived\fP\fC [get]\fP"
.br
.ti -1c
.RI "long \fBBytesSent\fP\fC [get]\fP"
.br
.ti -1c
.RI "long \fBBytesReceived\fP\fC [get]\fP"
.br
.ti -1c
.RI "long \fBPacketLoss\fP\fC [get]\fP"
.br
.ti -1c
.RI "long \fBPacketLossPercent\fP\fC [get]\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBNetStatistics\&.cs\fP 파일의 \fB5\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.AddBytesReceived (long bytesReceived)"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB70\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.AddBytesSent (long bytesSent)"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB65\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.AddPacketLoss (long packetLoss)"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB80\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.IncrementPacketLoss ()"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB75\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.IncrementPacketsReceived ()"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB60\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.IncrementPacketsSent ()"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB55\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.Reset ()"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB46\fP 번째 라인에서 정의되었습니다\&.
.SS "override string FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.ToString ()"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB85\fP 번째 라인에서 정의되었습니다\&.
.SH "속성 문서화"
.PP 
.SS "long FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.BytesReceived\fC [get]\fP"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB27\fP 번째 라인에서 정의되었습니다\&.
.SS "long FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.BytesSent\fC [get]\fP"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB23\fP 번째 라인에서 정의되었습니다\&.
.SS "long FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.PacketLoss\fC [get]\fP"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB31\fP 번째 라인에서 정의되었습니다\&.
.SS "long FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.PacketLossPercent\fC [get]\fP"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB36\fP 번째 라인에서 정의되었습니다\&.
.SS "long FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.PacketsReceived\fC [get]\fP"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB18\fP 번째 라인에서 정의되었습니다\&.
.SS "long FlyingWormConsole3\&.LiteNetLib\&.NetStatistics\&.PacketsSent\fC [get]\fP"

.PP
\fBNetStatistics\&.cs\fP 파일의 \fB13\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
