.TH "FlyingWormConsole3.LiteNetLib.Layers.Crc32cLayer" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib.Layers.Crc32cLayer
.SH SYNOPSIS
.br
.PP
.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.Layers\&.PacketLayerBase\fP를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBCrc32cLayer\fP ()"
.br
.ti -1c
.RI "override void \fBProcessInboundPacket\fP (IPEndPoint endPoint, ref byte[] data, ref int offset, ref int length)"
.br
.ti -1c
.RI "override void \fBProcessOutBoundPacket\fP (IPEndPoint endPoint, ref byte[] data, ref int offset, ref int length)"
.br
.in -1c
.SS "추가로 상속된 멤버들"
.SH "상세한 설명"
.PP 
\fBCrc32cLayer\&.cs\fP 파일의 \fB7\fP 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "FlyingWormConsole3\&.LiteNetLib\&.Layers\&.Crc32cLayer\&.Crc32cLayer ()"

.PP
\fBCrc32cLayer\&.cs\fP 파일의 \fB9\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "override void FlyingWormConsole3\&.LiteNetLib\&.Layers\&.Crc32cLayer\&.ProcessInboundPacket (IPEndPoint endPoint, ref byte[] data, ref int offset, ref int length)\fC [virtual]\fP"

.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.Layers\&.PacketLayerBase\fP를 구현\&.
.PP
\fBCrc32cLayer\&.cs\fP 파일의 \fB14\fP 번째 라인에서 정의되었습니다\&.
.SS "override void FlyingWormConsole3\&.LiteNetLib\&.Layers\&.Crc32cLayer\&.ProcessOutBoundPacket (IPEndPoint endPoint, ref byte[] data, ref int offset, ref int length)\fC [virtual]\fP"

.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.Layers\&.PacketLayerBase\fP를 구현\&.
.PP
\fBCrc32cLayer\&.cs\fP 파일의 \fB35\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
