.TH "FlyingWormConsole3.LiteNetLib.Utils.NtpPacket" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib.Utils.NtpPacket \- Represents RFC4330 SNTP packet used for communication to and from a network time server\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBNtpPacket\fP ()"
.br
.RI "Initializes default request packet\&. "
.in -1c
.SS "정적 Public 멤버 함수"

.in +1c
.ti -1c
.RI "static \fBNtpPacket\fP \fBFromServerResponse\fP (byte[] bytes, DateTime destinationTimestamp)"
.br
.RI "Initializes packet from data received from a server\&. "
.in -1c
.SS "속성"

.in +1c
.ti -1c
.RI "byte[] \fBBytes\fP\fC [get]\fP"
.br
.RI "Gets RFC4330-encoded SNTP packet\&. "
.ti -1c
.RI "\fBNtpLeapIndicator\fP \fBLeapIndicator\fP\fC [get]\fP"
.br
.RI "Gets the leap second indicator\&. "
.ti -1c
.RI "int \fBVersionNumber\fP\fC [get]\fP"
.br
.RI "Gets or sets protocol version number\&. "
.ti -1c
.RI "\fBNtpMode\fP \fBMode\fP\fC [get]\fP"
.br
.RI "Gets or sets SNTP packet mode, i\&.e\&. whether this is client or server packet\&. "
.ti -1c
.RI "int \fBStratum\fP\fC [get]\fP"
.br
.RI "Gets server's distance from the reference clock\&. "
.ti -1c
.RI "int \fBPoll\fP\fC [get]\fP"
.br
.RI "Gets server's preferred polling interval\&. "
.ti -1c
.RI "int \fBPrecision\fP\fC [get]\fP"
.br
.RI "Gets the precision of server clock\&. "
.ti -1c
.RI "TimeSpan \fBRootDelay\fP\fC [get]\fP"
.br
.RI "Gets the total round-trip delay from the server to the reference clock\&. "
.ti -1c
.RI "TimeSpan \fBRootDispersion\fP\fC [get]\fP"
.br
.RI "Gets the estimated error in time reported by the server\&. "
.ti -1c
.RI "uint \fBReferenceId\fP\fC [get]\fP"
.br
.RI "Gets the ID of the time source used by the server or Kiss-o'-Death code sent by the server\&. "
.ti -1c
.RI "DateTime? \fBReferenceTimestamp\fP\fC [get]\fP"
.br
.RI "Gets or sets the time when the server clock was last set or corrected\&. "
.ti -1c
.RI "DateTime? \fBOriginTimestamp\fP\fC [get]\fP"
.br
.RI "Gets or sets the time when the client sent its request\&. "
.ti -1c
.RI "DateTime? \fBReceiveTimestamp\fP\fC [get]\fP"
.br
.RI "Gets or sets the time when the request was received by the server\&. "
.ti -1c
.RI "DateTime? \fBTransmitTimestamp\fP\fC [get]\fP"
.br
.RI "Gets or sets the time when the packet was sent\&. "
.ti -1c
.RI "DateTime? \fBDestinationTimestamp\fP\fC [get]\fP"
.br
.RI "Gets or sets the time of reception of response SNTP packet on the client\&. "
.ti -1c
.RI "TimeSpan \fBRoundTripTime\fP\fC [get]\fP"
.br
.RI "Gets the round-trip time to the server\&. "
.ti -1c
.RI "TimeSpan \fBCorrectionOffset\fP\fC [get]\fP"
.br
.RI "Gets the offset that should be added to local time to synchronize it with server time\&. "
.in -1c
.SH "상세한 설명"
.PP 
Represents RFC4330 SNTP packet used for communication to and from a network time server\&. 

Most applications should just use the \fBNtpPacket\&.CorrectionOffset\fP property\&. 
.PP
The same data structure represents both request and reply packets\&. Request and reply differ in which properties are set and to what values\&. 
.PP
The only real property is \fBNtpPacket\&.Bytes\fP\&. All other properties read from and write to the underlying byte array with the exception of \fBNtpPacket\&.DestinationTimestamp\fP, which is not part of the packet on network and it is instead set locally after receiving the packet\&. 
.PP
Copied from \fCGuerrillaNtp project\fP with permission from Robert Vazan (@robertvazan) under MIT license, see https://github.com/RevenantX/LiteNetLib/pull/236 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB27\fP 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.NtpPacket ()"

.PP
Initializes default request packet\&. Properties \fBNtpPacket\&.Mode\fP and \fBNtpPacket\&.VersionNumber\fP are set appropriately for request packet\&. Property \fBNtpPacket\&.TransmitTimestamp\fP is set to System\&.DateTime\&.UtcNow\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB271\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "static \fBNtpPacket\fP FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.FromServerResponse (byte[] bytes, DateTime destinationTimestamp)\fC [static]\fP"

.PP
Initializes packet from data received from a server\&. 
.PP
\fB매개변수\fP
.RS 4
\fIbytes\fP Data received from the server\&.
.br
\fIdestinationTimestamp\fP Utc time of reception of response SNTP packet on the client\&.
.RE
.PP
\fB반환값\fP
.RS 4
.RE
.PP

.PP
\fBNtpPacket\&.cs\fP 파일의 \fB294\fP 번째 라인에서 정의되었습니다\&.
.SH "속성 문서화"
.PP 
.SS "byte [] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.Bytes\fC [get]\fP"

.PP
Gets RFC4330-encoded SNTP packet\&. Byte array containing RFC4330-encoded SNTP packet\&. It is at least 48 bytes long\&. 
.PP
This is the only real property\&. All other properties except \fBNtpPacket\&.DestinationTimestamp\fP read from or write to this byte array\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB41\fP 번째 라인에서 정의되었습니다\&.
.SS "TimeSpan FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.CorrectionOffset\fC [get]\fP"

.PP
Gets the offset that should be added to local time to synchronize it with server time\&. Time difference between server and client\&. It should be added to local time to get server time\&. It is calculated from timestamps in the packet as \fC0\&.5 * ((t1 - t0) - (t3 - t2))\fP where t0 is \fBNtpPacket\&.OriginTimestamp\fP, t1 is \fBNtpPacket\&.ReceiveTimestamp\fP, t2 is \fBNtpPacket\&.TransmitTimestamp\fP, and t3 is \fBNtpPacket\&.DestinationTimestamp\fP\&. This property throws an exception in request packets\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB254\fP 번째 라인에서 정의되었습니다\&.
.SS "DateTime? FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.DestinationTimestamp\fC [get]\fP"

.PP
Gets or sets the time of reception of response SNTP packet on the client\&. Time of reception of response SNTP packet on the client\&. It is \fCnull\fP in request packets\&. 
.PP
This property is not part of the protocol and has to be set when reply packet is received\&. 
.PP
\fB참고\fP
.RS 4
\fBNtpPacket\&.CorrectionOffset\fP, \fBNtpPacket\&.RoundTripTime\fP
.PP
.RE
.PP

.PP
\fBNtpPacket\&.cs\fP 파일의 \fB219\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBNtpLeapIndicator\fP FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.LeapIndicator\fC [get]\fP"

.PP
Gets the leap second indicator\&. Leap second warning, if any\&. Special value \fBNtpLeapIndicator\&.AlarmCondition\fP indicates unsynchronized server clock\&. Default is \fBNtpLeapIndicator\&.NoWarning\fP\&. 
.PP
Only servers fill in this property\&. Clients can consult this property for possible leap second warning\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB54\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBNtpMode\fP FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.Mode\fC [get]\fP"

.PP
Gets or sets SNTP packet mode, i\&.e\&. whether this is client or server packet\&. SNTP packet mode\&. Default is \fBNtpMode\&.Client\fP in newly created packets\&. Server reply should have this property set to \fBNtpMode\&.Server\fP\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB82\fP 번째 라인에서 정의되었습니다\&.
.SS "DateTime? FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.OriginTimestamp\fC [get]\fP"

.PP
Gets or sets the time when the client sent its request\&. This property is \fCnull\fP in request packets\&. In reply packets, it is the time when the client sent its request\&. Servers copy this value from \fBNtpPacket\&.TransmitTimestamp\fP that they find in received request packet\&. 
.PP
\fB참고\fP
.RS 4
\fBNtpPacket\&.CorrectionOffset\fP, \fBNtpPacket\&.RoundTripTime\fP
.PP
.RE
.PP

.PP
\fBNtpPacket\&.cs\fP 파일의 \fB181\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.Poll\fC [get]\fP"

.PP
Gets server's preferred polling interval\&. Polling interval in log2 seconds, e\&.g\&. 4 stands for 16s and 17 means 131,072s\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB110\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.Precision\fC [get]\fP"

.PP
Gets the precision of server clock\&. Clock precision in log2 seconds, e\&.g\&. -20 for microsecond precision\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB118\fP 번째 라인에서 정의되었습니다\&.
.SS "DateTime? FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.ReceiveTimestamp\fC [get]\fP"

.PP
Gets or sets the time when the request was received by the server\&. This property is \fCnull\fP in request packets\&. In reply packets, it is the time when the server received client request\&. 
.PP
\fB참고\fP
.RS 4
\fBNtpPacket\&.CorrectionOffset\fP, \fBNtpPacket\&.RoundTripTime\fP
.PP
.RE
.PP

.PP
\fBNtpPacket\&.cs\fP 파일의 \fB192\fP 번째 라인에서 정의되었습니다\&.
.SS "uint FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.ReferenceId\fC [get]\fP"

.PP
Gets the ID of the time source used by the server or Kiss-o'-Death code sent by the server\&. ID of server's time source or Kiss-o'-Death code\&. Purpose of this property depends on value of \fBNtpPacket\&.Stratum\fP property\&. 
.PP
Stratum 1 servers write here one of several special values that describe the kind of hardware clock they use\&. 
.PP
Stratum 2 and lower servers set this property to IPv4 address of their upstream server\&. If upstream server has IPv6 address, the address is hashed, because it doesn't fit in this property\&. 
.PP
When server sets \fBNtpPacket\&.Stratum\fP to special value 0, this property contains so called kiss code that instructs the client to stop querying the server\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB156\fP 번째 라인에서 정의되었습니다\&.
.SS "DateTime? FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.ReferenceTimestamp\fC [get]\fP"

.PP
Gets or sets the time when the server clock was last set or corrected\&. Time when the server clock was last set or corrected or \fCnull\fP when not specified\&. 
.PP
This Property is usually set only by servers\&. It usually lags server's current time by several minutes, so don't use this property for time synchronization\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB168\fP 번째 라인에서 정의되었습니다\&.
.SS "TimeSpan FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.RootDelay\fC [get]\fP"

.PP
Gets the total round-trip delay from the server to the reference clock\&. Round-trip delay to the reference clock\&. Normally a positive value smaller than one second\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB126\fP 번째 라인에서 정의되었습니다\&.
.SS "TimeSpan FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.RootDispersion\fC [get]\fP"

.PP
Gets the estimated error in time reported by the server\&. Estimated error in time reported by the server\&. Normally a positive value smaller than one second\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB134\fP 번째 라인에서 정의되었습니다\&.
.SS "TimeSpan FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.RoundTripTime\fC [get]\fP"

.PP
Gets the round-trip time to the server\&. Time the request spent traveling to the server plus the time the reply spent traveling back\&. This is calculated from timestamps in the packet as \fC(t1 - t0) + (t3 - t2)\fP where t0 is \fBNtpPacket\&.OriginTimestamp\fP, t1 is \fBNtpPacket\&.ReceiveTimestamp\fP, t2 is \fBNtpPacket\&.TransmitTimestamp\fP, and t3 is \fBNtpPacket\&.DestinationTimestamp\fP\&. This property throws an exception in request packets\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB233\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.Stratum\fC [get]\fP"

.PP
Gets server's distance from the reference clock\&. Distance from the reference clock\&. This property is set only in server reply packets\&. Servers connected directly to reference clock hardware set this property to 1\&. Statum number is incremented by 1 on every hop down the NTP server hierarchy\&. 
.PP
Special value 0 indicates that this packet is a Kiss-o'-Death message with kiss code stored in \fBNtpPacket\&.ReferenceId\fP\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB102\fP 번째 라인에서 정의되었습니다\&.
.SS "DateTime? FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.TransmitTimestamp\fC [get]\fP"

.PP
Gets or sets the time when the packet was sent\&. Time when the packet was sent\&. It should never be \fCnull\fP\&. Default value is System\&.DateTime\&.UtcNow\&. 
.PP
This property must be set by both clients and servers\&. 
.PP
\fB참고\fP
.RS 4
\fBNtpPacket\&.CorrectionOffset\fP, \fBNtpPacket\&.RoundTripTime\fP
.PP
.RE
.PP

.PP
\fBNtpPacket\&.cs\fP 파일의 \fB206\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\&.VersionNumber\fC [get]\fP"

.PP
Gets or sets protocol version number\&. SNTP protocol version\&. Default is 4, which is the latest version at the time of this writing\&. 
.PP
In request packets, clients should leave this property at default value 4\&. Servers usually reply with the same protocol version\&. 
.PP
\fBNtpPacket\&.cs\fP 파일의 \fB69\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
