.TH "FlyingWormConsole3.LiteNetLib.Utils.NetDataReader" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib.Utils.NetDataReader
.SH SYNOPSIS
.br
.PP
.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.NetPacketReader\fP에 의해 상속되었습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "void \fBSkipBytes\fP (int count)"
.br
.ti -1c
.RI "void \fBSetSource\fP (\fBNetDataWriter\fP dataWriter)"
.br
.ti -1c
.RI "void \fBSetSource\fP (byte[] source)"
.br
.ti -1c
.RI "void \fBSetSource\fP (byte[] source, int offset)"
.br
.ti -1c
.RI "void \fBSetSource\fP (byte[] source, int offset, int maxSize)"
.br
.ti -1c
.RI "\fBNetDataReader\fP ()"
.br
.ti -1c
.RI "\fBNetDataReader\fP (\fBNetDataWriter\fP writer)"
.br
.ti -1c
.RI "\fBNetDataReader\fP (byte[] source)"
.br
.ti -1c
.RI "\fBNetDataReader\fP (byte[] source, int offset)"
.br
.ti -1c
.RI "\fBNetDataReader\fP (byte[] source, int offset, int maxSize)"
.br
.ti -1c
.RI "IPEndPoint \fBGetNetEndPoint\fP ()"
.br
.ti -1c
.RI "byte \fBGetByte\fP ()"
.br
.ti -1c
.RI "sbyte \fBGetSByte\fP ()"
.br
.ti -1c
.RI "bool[] \fBGetBoolArray\fP ()"
.br
.ti -1c
.RI "ushort[] \fBGetUShortArray\fP ()"
.br
.ti -1c
.RI "short[] \fBGetShortArray\fP ()"
.br
.ti -1c
.RI "long[] \fBGetLongArray\fP ()"
.br
.ti -1c
.RI "ulong[] \fBGetULongArray\fP ()"
.br
.ti -1c
.RI "int[] \fBGetIntArray\fP ()"
.br
.ti -1c
.RI "uint[] \fBGetUIntArray\fP ()"
.br
.ti -1c
.RI "float[] \fBGetFloatArray\fP ()"
.br
.ti -1c
.RI "double[] \fBGetDoubleArray\fP ()"
.br
.ti -1c
.RI "string[] \fBGetStringArray\fP ()"
.br
.ti -1c
.RI "string[] \fBGetStringArray\fP (int maxStringLength)"
.br
.ti -1c
.RI "bool \fBGetBool\fP ()"
.br
.ti -1c
.RI "char \fBGetChar\fP ()"
.br
.ti -1c
.RI "ushort \fBGetUShort\fP ()"
.br
.ti -1c
.RI "short \fBGetShort\fP ()"
.br
.ti -1c
.RI "long \fBGetLong\fP ()"
.br
.ti -1c
.RI "ulong \fBGetULong\fP ()"
.br
.ti -1c
.RI "int \fBGetInt\fP ()"
.br
.ti -1c
.RI "uint \fBGetUInt\fP ()"
.br
.ti -1c
.RI "float \fBGetFloat\fP ()"
.br
.ti -1c
.RI "double \fBGetDouble\fP ()"
.br
.ti -1c
.RI "string \fBGetString\fP (int maxLength)"
.br
.ti -1c
.RI "string \fBGetString\fP ()"
.br
.ti -1c
.RI "ArraySegment< byte > \fBGetRemainingBytesSegment\fP ()"
.br
.ti -1c
.RI "T \fBGet< T >\fP ()"
.br
.ti -1c
.RI "byte[] \fBGetRemainingBytes\fP ()"
.br
.ti -1c
.RI "void \fBGetBytes\fP (byte[] destination, int start, int count)"
.br
.ti -1c
.RI "void \fBGetBytes\fP (byte[] destination, int count)"
.br
.ti -1c
.RI "sbyte[] \fBGetSBytesWithLength\fP ()"
.br
.ti -1c
.RI "byte[] \fBGetBytesWithLength\fP ()"
.br
.ti -1c
.RI "byte \fBPeekByte\fP ()"
.br
.ti -1c
.RI "sbyte \fBPeekSByte\fP ()"
.br
.ti -1c
.RI "bool \fBPeekBool\fP ()"
.br
.ti -1c
.RI "char \fBPeekChar\fP ()"
.br
.ti -1c
.RI "ushort \fBPeekUShort\fP ()"
.br
.ti -1c
.RI "short \fBPeekShort\fP ()"
.br
.ti -1c
.RI "long \fBPeekLong\fP ()"
.br
.ti -1c
.RI "ulong \fBPeekULong\fP ()"
.br
.ti -1c
.RI "int \fBPeekInt\fP ()"
.br
.ti -1c
.RI "uint \fBPeekUInt\fP ()"
.br
.ti -1c
.RI "float \fBPeekFloat\fP ()"
.br
.ti -1c
.RI "double \fBPeekDouble\fP ()"
.br
.ti -1c
.RI "string \fBPeekString\fP (int maxLength)"
.br
.ti -1c
.RI "string \fBPeekString\fP ()"
.br
.ti -1c
.RI "bool \fBTryGetByte\fP (out byte result)"
.br
.ti -1c
.RI "bool \fBTryGetSByte\fP (out sbyte result)"
.br
.ti -1c
.RI "bool \fBTryGetBool\fP (out bool result)"
.br
.ti -1c
.RI "bool \fBTryGetChar\fP (out char result)"
.br
.ti -1c
.RI "bool \fBTryGetShort\fP (out short result)"
.br
.ti -1c
.RI "bool \fBTryGetUShort\fP (out ushort result)"
.br
.ti -1c
.RI "bool \fBTryGetInt\fP (out int result)"
.br
.ti -1c
.RI "bool \fBTryGetUInt\fP (out uint result)"
.br
.ti -1c
.RI "bool \fBTryGetLong\fP (out long result)"
.br
.ti -1c
.RI "bool \fBTryGetULong\fP (out ulong result)"
.br
.ti -1c
.RI "bool \fBTryGetFloat\fP (out float result)"
.br
.ti -1c
.RI "bool \fBTryGetDouble\fP (out double result)"
.br
.ti -1c
.RI "bool \fBTryGetString\fP (out string result)"
.br
.ti -1c
.RI "bool \fBTryGetStringArray\fP (out string[] result)"
.br
.ti -1c
.RI "bool \fBTryGetBytesWithLength\fP (out byte[] result)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Protected 속성"

.in +1c
.ti -1c
.RI "byte[] \fB_data\fP"
.br
.ti -1c
.RI "int \fB_position\fP"
.br
.ti -1c
.RI "int \fB_dataSize\fP"
.br
.in -1c
.SS "속성"

.in +1c
.ti -1c
.RI "byte[] \fBRawData\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBRawDataSize\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBUserDataOffset\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBUserDataSize\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsNull\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBPosition\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBEndOfData\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBAvailableBytes\fP\fC [get]\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBNetDataReader\&.cs\fP 파일의 \fB7\fP 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.NetDataReader ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB91\fP 번째 라인에서 정의되었습니다\&.
.SS "FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.NetDataReader (\fBNetDataWriter\fP writer)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB96\fP 번째 라인에서 정의되었습니다\&.
.SS "FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.NetDataReader (byte[] source)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB101\fP 번째 라인에서 정의되었습니다\&.
.SS "FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.NetDataReader (byte[] source, int offset)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB106\fP 번째 라인에서 정의되었습니다\&.
.SS "FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.NetDataReader (byte[] source, int offset, int maxSize)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB111\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.Clear ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB686\fP 번째 라인에서 정의되었습니다\&.
.SS "T FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.Get< T > ()"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetDataReader\&.cs\fP 파일의 \fB361\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetBool ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB252\fP 번째 라인에서 정의되었습니다\&.
.SS "bool[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetBoolArray ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB138\fP 번째 라인에서 정의되었습니다\&.
.SS "byte FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetByte ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB124\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetBytes (byte[] destination, int count)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB382\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetBytes (byte[] destination, int start, int count)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB376\fP 번째 라인에서 정의되었습니다\&.
.SS "byte[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetBytesWithLength ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB397\fP 번째 라인에서 정의되었습니다\&.
.SS "char FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetChar ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB259\fP 번째 라인에서 정의되었습니다\&.
.SS "double FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetDouble ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB315\fP 번째 라인에서 정의되었습니다\&.
.SS "double[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetDoubleArray ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB218\fP 번째 라인에서 정의되었습니다\&.
.SS "float FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetFloat ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB308\fP 번째 라인에서 정의되었습니다\&.
.SS "float[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetFloatArray ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB208\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetInt ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB294\fP 번째 라인에서 정의되었습니다\&.
.SS "int[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetIntArray ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB188\fP 번째 라인에서 정의되었습니다\&.
.SS "long FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetLong ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB280\fP 번째 라인에서 정의되었습니다\&.
.SS "long[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetLongArray ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB168\fP 번째 라인에서 정의되었습니다\&.
.SS "IPEndPoint FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetNetEndPoint ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB117\fP 번째 라인에서 정의되었습니다\&.
.SS "byte[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetRemainingBytes ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB368\fP 번째 라인에서 정의되었습니다\&.
.SS "ArraySegment< byte > FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetRemainingBytesSegment ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB354\fP 번째 라인에서 정의되었습니다\&.
.SS "sbyte FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetSByte ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB131\fP 번째 라인에서 정의되었습니다\&.
.SS "sbyte[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetSBytesWithLength ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB388\fP 번째 라인에서 정의되었습니다\&.
.SS "short FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetShort ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB273\fP 번째 라인에서 정의되었습니다\&.
.SS "short[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetShortArray ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB158\fP 번째 라인에서 정의되었습니다\&.
.SS "string FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetString ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB341\fP 번째 라인에서 정의되었습니다\&.
.SS "string FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetString (int maxLength)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB322\fP 번째 라인에서 정의되었습니다\&.
.SS "string[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetStringArray ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB228\fP 번째 라인에서 정의되었습니다\&.
.SS "string[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetStringArray (int maxStringLength)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB240\fP 번째 라인에서 정의되었습니다\&.
.SS "uint FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetUInt ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB301\fP 번째 라인에서 정의되었습니다\&.
.SS "uint[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetUIntArray ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB198\fP 번째 라인에서 정의되었습니다\&.
.SS "ulong FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetULong ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB287\fP 번째 라인에서 정의되었습니다\&.
.SS "ulong[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetULongArray ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB178\fP 번째 라인에서 정의되었습니다\&.
.SS "ushort FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetUShort ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB266\fP 번째 라인에서 정의되었습니다\&.
.SS "ushort[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.GetUShortArray ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB148\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekBool ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB419\fP 번째 라인에서 정의되었습니다\&.
.SS "byte FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekByte ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB409\fP 번째 라인에서 정의되었습니다\&.
.SS "char FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekChar ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB424\fP 번째 라인에서 정의되었습니다\&.
.SS "double FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekDouble ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB464\fP 번째 라인에서 정의되었습니다\&.
.SS "float FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekFloat ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB459\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekInt ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB449\fP 번째 라인에서 정의되었습니다\&.
.SS "long FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekLong ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB439\fP 번째 라인에서 정의되었습니다\&.
.SS "sbyte FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekSByte ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB414\fP 번째 라인에서 정의되었습니다\&.
.SS "short FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekShort ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB434\fP 번째 라인에서 정의되었습니다\&.
.SS "string FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekString ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB487\fP 번째 라인에서 정의되었습니다\&.
.SS "string FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekString (int maxLength)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB469\fP 번째 라인에서 정의되었습니다\&.
.SS "uint FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekUInt ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB454\fP 번째 라인에서 정의되었습니다\&.
.SS "ulong FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekULong ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB444\fP 번째 라인에서 정의되었습니다\&.
.SS "ushort FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.PeekUShort ()"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB429\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.SetSource (byte[] source)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB67\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.SetSource (byte[] source, int offset)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB75\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.SetSource (byte[] source, int offset, int maxSize)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB83\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.SetSource (\fBNetDataWriter\fP dataWriter)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB59\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.SkipBytes (int count)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB54\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetBool (out bool result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB523\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetByte (out byte result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB501\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetBytesWithLength (out byte[] result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB670\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetChar (out char result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB534\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetDouble (out double result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB622\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetFloat (out float result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB611\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetInt (out int result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB567\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetLong (out long result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB589\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetSByte (out sbyte result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB512\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetShort (out short result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB545\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetString (out string result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB633\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetStringArray (out string[] result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB648\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetUInt (out uint result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB578\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetULong (out ulong result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB600\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.TryGetUShort (out ushort result)"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB556\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 데이터 문서화"
.PP 
.SS "byte [] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&._data\fC [protected]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB9\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&._dataSize\fC [protected]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB11\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&._position\fC [protected]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB10\fP 번째 라인에서 정의되었습니다\&.
.SH "속성 문서화"
.PP 
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.AvailableBytes\fC [get]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB49\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.EndOfData\fC [get]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB44\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.IsNull\fC [get]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB34\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.Position\fC [get]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB39\fP 번째 라인에서 정의되었습니다\&.
.SS "byte [] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.RawData\fC [get]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB14\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.RawDataSize\fC [get]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB19\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.UserDataOffset\fC [get]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB24\fP 번째 라인에서 정의되었습니다\&.
.SS "int FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetDataReader\&.UserDataSize\fC [get]\fP"

.PP
\fBNetDataReader\&.cs\fP 파일의 \fB29\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
