.TH "FlyingWormConsole3.LiteNetLib.TooBigPacketException" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib.TooBigPacketException
.SH SYNOPSIS
.br
.PP
.PP
\fBFlyingWormConsole3\&.LiteNetLib\&.InvalidPacketException\fP를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBTooBigPacketException\fP (string message)"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBNetDebug\&.cs\fP 파일의 \fB13\fP 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "FlyingWormConsole3\&.LiteNetLib\&.TooBigPacketException\&.TooBigPacketException (string message)"

.PP
\fBNetDebug\&.cs\fP 파일의 \fB15\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
