.TH "FlyingWormConsole3.LiteNetLib.Utils.NetPacketProcessor" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib.Utils.NetPacketProcessor
.SH SYNOPSIS
.br
.PP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBNetPacketProcessor\fP ()"
.br
.ti -1c
.RI "\fBNetPacketProcessor\fP (int maxStringLength)"
.br
.ti -1c
.RI "void \fBRegisterNestedType< T >\fP ()"
.br
.RI "Register nested property type "
.ti -1c
.RI "void \fBRegisterNestedType< T >\fP (Action< \fBNetDataWriter\fP, T > writeDelegate, Func< \fBNetDataReader\fP, T > readDelegate)"
.br
.RI "Register nested property type "
.ti -1c
.RI "void \fBRegisterNestedType< T >\fP (Func< T > constructor)"
.br
.RI "Register nested property type "
.ti -1c
.RI "void \fBReadAllPackets\fP (\fBNetDataReader\fP reader)"
.br
.RI "Reads all available data from \fBNetDataReader\fP and calls OnReceive delegates "
.ti -1c
.RI "void \fBReadAllPackets\fP (\fBNetDataReader\fP reader, object userData)"
.br
.RI "Reads all available data from \fBNetDataReader\fP and calls OnReceive delegates "
.ti -1c
.RI "void \fBReadPacket\fP (\fBNetDataReader\fP reader)"
.br
.RI "Reads one packet from \fBNetDataReader\fP and calls OnReceive delegate "
.ti -1c
.RI "void \fBSend< T >\fP (\fBNetPeer\fP peer, T packet, \fBDeliveryMethod\fP options)"
.br
.ti -1c
.RI "void \fBSendNetSerializable< T >\fP (\fBNetPeer\fP peer, T packet, \fBDeliveryMethod\fP options)"
.br
.ti -1c
.RI "void \fBSend< T >\fP (\fBNetManager\fP manager, T packet, \fBDeliveryMethod\fP options)"
.br
.ti -1c
.RI "void \fBSendNetSerializable< T >\fP (\fBNetManager\fP manager, T packet, \fBDeliveryMethod\fP options)"
.br
.ti -1c
.RI "void \fBWrite< T >\fP (\fBNetDataWriter\fP writer, T packet)"
.br
.ti -1c
.RI "void \fBWriteNetSerializable< T >\fP (\fBNetDataWriter\fP writer, T packet)"
.br
.ti -1c
.RI "byte[] \fBWrite< T >\fP (T packet)"
.br
.ti -1c
.RI "byte[] \fBWriteNetSerializable< T >\fP (T packet)"
.br
.ti -1c
.RI "void \fBReadPacket\fP (\fBNetDataReader\fP reader, object userData)"
.br
.RI "Reads one packet from \fBNetDataReader\fP and calls OnReceive delegate "
.ti -1c
.RI "void \fBSubscribe< T >\fP (Action< T > onReceive, Func< T > packetConstructor)"
.br
.RI "Register and subscribe to packet receive event "
.ti -1c
.RI "void \fBSubscribe< T, TUserData >\fP (Action< T, TUserData > onReceive, Func< T > packetConstructor)"
.br
.RI "Register and subscribe to packet receive event (with userData) "
.ti -1c
.RI "void \fBSubscribeReusable< T >\fP (Action< T > onReceive)"
.br
.RI "Register and subscribe to packet receive event This method will overwrite last received packet class on receive (less garbage) "
.ti -1c
.RI "void \fBSubscribeReusable< T, TUserData >\fP (Action< T, TUserData > onReceive)"
.br
.RI "Register and subscribe to packet receive event This method will overwrite last received packet class on receive (less garbage) "
.ti -1c
.RI "void \fBSubscribeNetSerializable< T, TUserData >\fP (Action< T, TUserData > onReceive, Func< T > packetConstructor)"
.br
.ti -1c
.RI "void \fBSubscribeNetSerializable< T >\fP (Action< T > onReceive, Func< T > packetConstructor)"
.br
.ti -1c
.RI "void \fBSubscribeNetSerializable< T, TUserData >\fP (Action< T, TUserData > onReceive)"
.br
.ti -1c
.RI "void \fBSubscribeNetSerializable< T >\fP (Action< T > onReceive)"
.br
.ti -1c
.RI "bool \fBRemoveSubscription< T >\fP ()"
.br
.RI "Remove any subscriptions by type "
.in -1c
.SS "Protected 멤버 함수"

.in +1c
.ti -1c
.RI "delegate void \fBSubscribeDelegate\fP (\fBNetDataReader\fP reader, object userData)"
.br
.ti -1c
.RI "virtual ulong \fBGetHash< T >\fP ()"
.br
.ti -1c
.RI "virtual \fBSubscribeDelegate\fP \fBGetCallbackFromData\fP (\fBNetDataReader\fP reader)"
.br
.ti -1c
.RI "virtual void \fBWriteHash< T >\fP (\fBNetDataWriter\fP writer)"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBNetPacketProcessor\&.cs\fP 파일의 \fB6\fP 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.NetPacketProcessor ()"

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB31\fP 번째 라인에서 정의되었습니다\&.
.SS "FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.NetPacketProcessor (int maxStringLength)"

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB36\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "virtual \fBSubscribeDelegate\fP FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.GetCallbackFromData (\fBNetDataReader\fP reader)\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB46\fP 번째 라인에서 정의되었습니다\&.
.SS "virtual ulong FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.GetHash< T > ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB41\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.ReadAllPackets (\fBNetDataReader\fP reader)"

.PP
Reads all available data from \fBNetDataReader\fP and calls OnReceive delegates 
.PP
\fB매개변수\fP
.RS 4
\fIreader\fP \fBNetDataReader\fP with packets data
.RE
.PP

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB94\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.ReadAllPackets (\fBNetDataReader\fP reader, object userData)"

.PP
Reads all available data from \fBNetDataReader\fP and calls OnReceive delegates 
.PP
\fB매개변수\fP
.RS 4
\fIreader\fP \fBNetDataReader\fP with packets data
.br
\fIuserData\fP Argument that passed to OnReceivedEvent
.RE
.PP
\fB예외\fP
.RS 4
\fI\fBParseException\fP\fP Malformed packet
.RE
.PP

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB106\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.ReadPacket (\fBNetDataReader\fP reader)"

.PP
Reads one packet from \fBNetDataReader\fP and calls OnReceive delegate 
.PP
\fB매개변수\fP
.RS 4
\fIreader\fP \fBNetDataReader\fP with packet
.RE
.PP
\fB예외\fP
.RS 4
\fI\fBParseException\fP\fP Malformed packet
.RE
.PP

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB117\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.ReadPacket (\fBNetDataReader\fP reader, object userData)"

.PP
Reads one packet from \fBNetDataReader\fP and calls OnReceive delegate 
.PP
\fB매개변수\fP
.RS 4
\fIreader\fP \fBNetDataReader\fP with packet
.br
\fIuserData\fP Argument that passed to OnReceivedEvent
.RE
.PP
\fB예외\fP
.RS 4
\fI\fBParseException\fP\fP Malformed packet
.RE
.PP

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB184\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.RegisterNestedType< T > ()"

.PP
Register nested property type 
.PP
\fB템플릿 파라메터\fP
.RS 4
\fIT\fP \fBINetSerializable\fP structure
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIstruct\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB66\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.RegisterNestedType< T > (Action< \fBNetDataWriter\fP, T > writeDelegate, Func< \fBNetDataReader\fP, T > readDelegate)"

.PP
Register nested property type 
.PP
\fB매개변수\fP
.RS 4
\fIwriteDelegate\fP 
.br
\fIreadDelegate\fP 
.RE
.PP

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB76\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.RegisterNestedType< T > (Func< T > constructor)"

.PP
Register nested property type 
.PP
\fB템플릿 파라메터\fP
.RS 4
\fIT\fP \fBINetSerializable\fP class
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB85\fP 번째 라인에서 정의되었습니다\&.
.SS "bool FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.RemoveSubscription< T > ()"

.PP
Remove any subscriptions by type 
.PP
\fB템플릿 파라메터\fP
.RS 4
\fIT\fP Packet type
.RE
.PP
\fB반환값\fP
.RS 4
true if remove is success
.RE
.PP

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB308\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.Send< T > (\fBNetManager\fP manager, T packet, \fBDeliveryMethod\fP options)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB136\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.Send< T > (\fBNetPeer\fP peer, T packet, \fBDeliveryMethod\fP options)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB122\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.SendNetSerializable< T > (\fBNetManager\fP manager, T packet, \fBDeliveryMethod\fP options)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB143\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.SendNetSerializable< T > (\fBNetPeer\fP peer, T packet, \fBDeliveryMethod\fP options)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB129\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.Subscribe< T > (Action< T > onReceive, Func< T > packetConstructor)"

.PP
Register and subscribe to packet receive event 
.PP
\fB매개변수\fP
.RS 4
\fIonReceive\fP event that will be called when packet deserialized with ReadPacket method
.br
\fIpacketConstructor\fP Method that constructs packet instead of slow Activator\&.CreateInstance
.RE
.PP
\fB예외\fP
.RS 4
\fI\fBInvalidTypeException\fP\fP \fIT\fP 's fields are not supported, or it has no fields
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB195\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.Subscribe< T, TUserData > (Action< T, TUserData > onReceive, Func< T > packetConstructor)"

.PP
Register and subscribe to packet receive event (with userData) 
.PP
\fB매개변수\fP
.RS 4
\fIonReceive\fP event that will be called when packet deserialized with ReadPacket method
.br
\fIpacketConstructor\fP Method that constructs packet instead of slow Activator\&.CreateInstance
.RE
.PP
\fB예외\fP
.RS 4
\fI\fBInvalidTypeException\fP\fP \fIT\fP 's fields are not supported, or it has no fields
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB212\fP 번째 라인에서 정의되었습니다\&.
.SS "delegate void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.SubscribeDelegate (\fBNetDataReader\fP reader, object userData)\fC [protected]\fP"

.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.SubscribeNetSerializable< T > (Action< T > onReceive)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB292\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.SubscribeNetSerializable< T > (Action< T > onReceive, Func< T > packetConstructor)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB269\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.SubscribeNetSerializable< T, TUserData > (Action< T, TUserData > onReceive)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB281\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.SubscribeNetSerializable< T, TUserData > (Action< T, TUserData > onReceive, Func< T > packetConstructor)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB257\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.SubscribeReusable< T > (Action< T > onReceive)"

.PP
Register and subscribe to packet receive event This method will overwrite last received packet class on receive (less garbage) 
.PP
\fB매개변수\fP
.RS 4
\fIonReceive\fP event that will be called when packet deserialized with ReadPacket method
.RE
.PP
\fB예외\fP
.RS 4
\fI\fBInvalidTypeException\fP\fP \fIT\fP 's fields are not supported, or it has no fields
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB229\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.SubscribeReusable< T, TUserData > (Action< T, TUserData > onReceive)"

.PP
Register and subscribe to packet receive event This method will overwrite last received packet class on receive (less garbage) 
.PP
\fB매개변수\fP
.RS 4
\fIonReceive\fP event that will be called when packet deserialized with ReadPacket method
.RE
.PP
\fB예외\fP
.RS 4
\fI\fBInvalidTypeException\fP\fP \fIT\fP 's fields are not supported, or it has no fields
.RE
.PP

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB246\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.Write< T > (\fBNetDataWriter\fP writer, T packet)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB150\fP 번째 라인에서 정의되었습니다\&.
.SS "byte[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.Write< T > (T packet)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fInew()\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB162\fP 번째 라인에서 정의되었습니다\&.
.SS "virtual void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.WriteHash< T > (\fBNetDataWriter\fP writer)\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB57\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.WriteNetSerializable< T > (\fBNetDataWriter\fP writer, T packet)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB156\fP 번째 라인에서 정의되었습니다\&.
.SS "byte[] FlyingWormConsole3\&.LiteNetLib\&.Utils\&.NetPacketProcessor\&.WriteNetSerializable< T > (T packet)"

.PP
\fB타입 한정자들\fP
.TP
\fIT\fP : \fIINetSerializable\fP
.PP
\fBNetPacketProcessor\&.cs\fP 파일의 \fB170\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
