.TH "FlyingWormConsole3.LiteNetLib.NatPunchModule" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlyingWormConsole3.LiteNetLib.NatPunchModule \- Module for UDP NAT Hole punching operations\&. Can be accessed from \fBNetManager\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "void \fBInit\fP (\fBINatPunchListener\fP listener)"
.br
.ti -1c
.RI "void \fBNatIntroduce\fP (IPEndPoint hostInternal, IPEndPoint hostExternal, IPEndPoint clientInternal, IPEndPoint clientExternal, string additionalInfo)"
.br
.ti -1c
.RI "void \fBPollEvents\fP ()"
.br
.ti -1c
.RI "void \fBSendNatIntroduceRequest\fP (string host, int port, string additionalInfo)"
.br
.ti -1c
.RI "void \fBSendNatIntroduceRequest\fP (IPEndPoint masterServerEndPoint, string additionalInfo)"
.br
.in -1c
.SS "정적 Public 속성"

.in +1c
.ti -1c
.RI "const int \fBMaxTokenLength\fP = 256"
.br
.in -1c
.SH "상세한 설명"
.PP 
Module for UDP NAT Hole punching operations\&. Can be accessed from \fBNetManager\fP 
.PP
\fBNatPunchModule\&.cs\fP 파일의 \fB44\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NatPunchModule\&.Init (\fBINatPunchListener\fP listener)"

.PP
\fBNatPunchModule\&.cs\fP 파일의 \fB105\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NatPunchModule\&.NatIntroduce (IPEndPoint hostInternal, IPEndPoint hostExternal, IPEndPoint clientInternal, IPEndPoint clientExternal, string additionalInfo)"

.PP
\fBNatPunchModule\&.cs\fP 파일의 \fB119\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NatPunchModule\&.PollEvents ()"

.PP
\fBNatPunchModule\&.cs\fP 파일의 \fB142\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NatPunchModule\&.SendNatIntroduceRequest (IPEndPoint masterServerEndPoint, string additionalInfo)"

.PP
\fBNatPunchModule\&.cs\fP 파일의 \fB172\fP 번째 라인에서 정의되었습니다\&.
.SS "void FlyingWormConsole3\&.LiteNetLib\&.NatPunchModule\&.SendNatIntroduceRequest (string host, int port, string additionalInfo)"

.PP
\fBNatPunchModule\&.cs\fP 파일의 \fB167\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 데이터 문서화"
.PP 
.SS "const int FlyingWormConsole3\&.LiteNetLib\&.NatPunchModule\&.MaxTokenLength = 256\fC [static]\fP"

.PP
\fBNatPunchModule\&.cs\fP 파일의 \fB86\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
