.TH "Assets/ConsolePro/Remote/LiteNetLib/INetEventListener.cs" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/ConsolePro/Remote/LiteNetLib/INetEventListener.cs
.SH SYNOPSIS
.br
.PP
.SS "클래스"

.in +1c
.ti -1c
.RI "struct \fBFlyingWormConsole3\&.LiteNetLib\&.DisconnectInfo\fP"
.br
.RI "Additional information about disconnection "
.ti -1c
.RI "interface \fBFlyingWormConsole3\&.LiteNetLib\&.INetEventListener\fP"
.br
.ti -1c
.RI "interface \fBFlyingWormConsole3\&.LiteNetLib\&.IDeliveryEventListener\fP"
.br
.ti -1c
.RI "interface \fBFlyingWormConsole3\&.LiteNetLib\&.INtpEventListener\fP"
.br
.ti -1c
.RI "class \fBFlyingWormConsole3\&.LiteNetLib\&.EventBasedNetListener\fP"
.br
.in -1c
.SS "네임스페이스"

.in +1c
.ti -1c
.RI "namespace \fBFlyingWormConsole3\fP"
.br
.ti -1c
.RI "namespace \fBFlyingWormConsole3\&.LiteNetLib\fP"
.br
.in -1c
.SS "열거형 타입"

.in +1c
.ti -1c
.RI "enum \fBFlyingWormConsole3\&.LiteNetLib\&.UnconnectedMessageType\fP { \fBFlyingWormConsole3\&.LiteNetLib\&.BasicMessage\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.Broadcast\fP }"
.br
.RI "Type of message that you receive in OnNetworkReceiveUnconnected event "
.ti -1c
.RI "enum \fBFlyingWormConsole3\&.LiteNetLib\&.DisconnectReason\fP { \fBFlyingWormConsole3\&.LiteNetLib\&.ConnectionFailed\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.Timeout\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.HostUnreachable\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.NetworkUnreachable\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.RemoteConnectionClose\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.DisconnectPeerCalled\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.ConnectionRejected\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.InvalidProtocol\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.UnknownHost\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.Reconnect\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.PeerToPeerConnection\fP }"
.br
.RI "Disconnect reason that you receive in OnPeerDisconnected event "
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
