.TH "Assets/ConsolePro/Remote/LiteNetLib/NetDebug.cs" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/ConsolePro/Remote/LiteNetLib/NetDebug.cs
.SH SYNOPSIS
.br
.PP
.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBFlyingWormConsole3\&.LiteNetLib\&.InvalidPacketException\fP"
.br
.ti -1c
.RI "class \fBFlyingWormConsole3\&.LiteNetLib\&.TooBigPacketException\fP"
.br
.ti -1c
.RI "interface \fBFlyingWormConsole3\&.LiteNetLib\&.INetLogger\fP"
.br
.RI "Interface to implement for your own logger "
.ti -1c
.RI "class \fBFlyingWormConsole3\&.LiteNetLib\&.NetDebug\fP"
.br
.RI "Static class for defining your own \fBLiteNetLib\fP logger instead of Console\&.WriteLine or Debug\&.Log if compiled with UNITY flag "
.in -1c
.SS "네임스페이스"

.in +1c
.ti -1c
.RI "namespace \fBFlyingWormConsole3\fP"
.br
.ti -1c
.RI "namespace \fBFlyingWormConsole3\&.LiteNetLib\fP"
.br
.in -1c
.SS "열거형 타입"

.in +1c
.ti -1c
.RI "enum \fBFlyingWormConsole3\&.LiteNetLib\&.NetLogLevel\fP { \fBFlyingWormConsole3\&.LiteNetLib\&.Warning\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.Error\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.Trace\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.Info\fP }"
.br
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
