.TH "Assets/ConsolePro/Remote/LiteNetLib/NetManager.cs" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/ConsolePro/Remote/LiteNetLib/NetManager.cs
.SH SYNOPSIS
.br
.PP
.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBFlyingWormConsole3\&.LiteNetLib\&.NetPacketReader\fP"
.br
.ti -1c
.RI "class \fBFlyingWormConsole3\&.LiteNetLib\&.NetEvent\fP"
.br
.ti -1c
.RI "class \fBFlyingWormConsole3\&.LiteNetLib\&.NetManager\fP"
.br
.RI "Main class for all network operations\&. Can be used as client and/or server\&. "
.ti -1c
.RI "struct \fBFlyingWormConsole3\&.LiteNetLib\&.NetManager\&.NetPeerEnumerator\fP"
.br
.in -1c
.SS "네임스페이스"

.in +1c
.ti -1c
.RI "namespace \fBFlyingWormConsole3\fP"
.br
.ti -1c
.RI "namespace \fBFlyingWormConsole3\&.LiteNetLib\fP"
.br
.in -1c
.SS "열거형 타입"

.in +1c
.ti -1c
.RI "enum \fBFlyingWormConsole3\&.LiteNetLib\&.IPv6Mode\fP { \fBFlyingWormConsole3\&.LiteNetLib\&.Disabled\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.SeparateSocket\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.DualMode\fP }"
.br
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
