.TH "Assets/ConsolePro/Remote/LiteNetLib/NetPeer.cs" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/ConsolePro/Remote/LiteNetLib/NetPeer.cs
.SH SYNOPSIS
.br
.PP
.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBFlyingWormConsole3\&.LiteNetLib\&.NetPeer\fP"
.br
.RI "Network peer\&. Main purpose is sending messages to specific peer\&. "
.in -1c
.SS "네임스페이스"

.in +1c
.ti -1c
.RI "namespace \fBFlyingWormConsole3\fP"
.br
.ti -1c
.RI "namespace \fBFlyingWormConsole3\&.LiteNetLib\fP"
.br
.in -1c
.SS "열거형 타입"

.in +1c
.ti -1c
.RI "enum \fBFlyingWormConsole3\&.LiteNetLib\&.ConnectionState\fP : byte { \fBFlyingWormConsole3\&.LiteNetLib\&.Outgoing\fP = 1 << 1, \fBFlyingWormConsole3\&.LiteNetLib\&.Connected\fP = 1 << 2, \fBFlyingWormConsole3\&.LiteNetLib\&.ShutdownRequested\fP = 1 << 3, \fBFlyingWormConsole3\&.LiteNetLib\&.Disconnected\fP = 1 << 4, \fBFlyingWormConsole3\&.LiteNetLib\&.Any\fP = Outgoing | Connected | ShutdownRequested }"
.br
.RI "Peer connection state "
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
