.TH "Assets/ConsolePro/Remote/LiteNetLib/NetUtils.cs" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/ConsolePro/Remote/LiteNetLib/NetUtils.cs
.SH SYNOPSIS
.br
.PP
.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBFlyingWormConsole3\&.LiteNetLib\&.NetUtils\fP"
.br
.RI "Some specific network utilities "
.in -1c
.SS "네임스페이스"

.in +1c
.ti -1c
.RI "namespace \fBFlyingWormConsole3\fP"
.br
.ti -1c
.RI "namespace \fBFlyingWormConsole3\&.LiteNetLib\fP"
.br
.in -1c
.SS "열거형 타입"

.in +1c
.ti -1c
.RI "enum \fBFlyingWormConsole3\&.LiteNetLib\&.LocalAddrType\fP { \fBFlyingWormConsole3\&.LiteNetLib\&.IPv4\fP = 1, \fBFlyingWormConsole3\&.LiteNetLib\&.IPv6\fP = 2, \fBFlyingWormConsole3\&.LiteNetLib\&.All\fP = IPv4 | IPv6 }"
.br
.RI "Address type that you want to receive from NetUtils\&.GetLocalIp method "
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
