.TH "Assets/ConsolePro/Remote/LiteNetLib/Utils/NtpPacket.cs" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets/ConsolePro/Remote/LiteNetLib/Utils/NtpPacket.cs
.SH SYNOPSIS
.br
.PP
.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBFlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpPacket\fP"
.br
.RI "Represents RFC4330 SNTP packet used for communication to and from a network time server\&. "
.in -1c
.SS "네임스페이스"

.in +1c
.ti -1c
.RI "namespace \fBFlyingWormConsole3\fP"
.br
.ti -1c
.RI "namespace \fBFlyingWormConsole3\&.LiteNetLib\fP"
.br
.ti -1c
.RI "namespace \fBFlyingWormConsole3\&.LiteNetLib\&.Utils\fP"
.br
.in -1c
.SS "열거형 타입"

.in +1c
.ti -1c
.RI "enum \fBFlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpLeapIndicator\fP { \fBFlyingWormConsole3\&.LiteNetLib\&.Utils\&.NoWarning\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.Utils\&.LastMinuteHas61Seconds\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.Utils\&.LastMinuteHas59Seconds\fP, \fBFlyingWormConsole3\&.LiteNetLib\&.Utils\&.AlarmCondition\fP }"
.br
.RI "Represents leap second warning from the server that instructs the client to add or remove leap second\&. "
.ti -1c
.RI "enum \fBFlyingWormConsole3\&.LiteNetLib\&.Utils\&.NtpMode\fP { \fBFlyingWormConsole3\&.LiteNetLib\&.Utils\&.Client\fP = 3, \fBFlyingWormConsole3\&.LiteNetLib\&.Utils\&.Server\fP = 4 }"
.br
.RI "Describes SNTP packet mode, i\&.e\&. client or server\&. "
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
