.TH "TestNamespace.TestDoxygen" 3 "금 6월 24 2022" "Version 1.0" "Unity 3D Game Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestNamespace.TestDoxygen \- class 간략한 설명  

.SH SYNOPSIS
.br
.PP
.PP
MonoBehaviour를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "void \fBTestFunc\fP (int a, int b)"
.br
.RI "메서드 간략 설명 "
.in -1c
.SH "상세한 설명"
.PP 
class 간략한 설명 

class 자세한 설명 
.PP
\fB작성자\fP
.RS 4
writer name(코드 작성자 이름) 
.RE
.PP
\fB날짜\fP
.RS 4
2022-06-24 
.RE
.PP
\fB버전\fP
.RS 4
1\&.0 
.RE
.PP

.PP
\fBTestDoxygen\&.cs\fP 파일의 \fB18\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "void TestNamespace\&.TestDoxygen\&.TestFunc (int a, int b)"

.PP
메서드 간략 설명 메서드 상세 설명 
.PP
\fB매개변수\fP
.RS 4
\fIa\fP <- 매개변수 1 
.br
\fIb\fP <- 매개변수 2 
.br
\fIc\fP <- 만약 포인터등이 전달되거나 반환값이 있으면 표시 
.RE
.PP
\fB반환값\fP
.RS 4
void <- 함수가 void니까 
.RE
.PP
\fB예외\fP
.RS 4
\fI예외처리를\fP 설명(이 함수에는 예외가 없습니다\&.) 
.br
\fIthrows하는\fP 객체나 변수등을 설명
.RE
.PP
\fB주의\fP
.RS 4
참고 설명 
.RE
.PP
\fB할일\fP
.RS 4
할 일 설명 
.RE
.PP
\fB전제조건\fP
.RS 4
미리 호출해야 할 사항 
.RE
.PP
\fB버그\fP
.RS 4
버그 설명 
.RE
.PP
\fB경고\fP
.RS 4
주의 사항 작성 
.RE
.PP
\fB참고\fP
.RS 4
참고할 함수 또는 페이지 (페이지나 함수 이름을 작성하면 자동 링크)
.RE
.PP
.PP
.nf
중요코드를 설명할때 시작 지점을 가리킵니다\&.
.fi
.PP
 중요코드를 설명할때 종료 지점을 가리킵니다\&. 
.PP
\fBTestDoxygen\&.cs\fP 파일의 \fB53\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Unity 3D Game Doxygen를 위해 Doxygen에 의해 자동으로 생성됨\&.
